name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.20.0, 14.x, 16.x, 18.x]
        os: [windows-lattest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js For Build
        uses: actions/setup-node@v3.4.1
        with:
          node-version-file: ".nvmrc"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run bulid

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Test For Node12+
        if: matrix.node-version != '12.20.0'
        run: pnpm test

      - name: Test For Node12
        if: matrix.node-version == '12.20.0'
        run: pnpm test-downgrade
